### PR TITLE
Merge template repo and added model binding functionality

### PR DESCRIPTION
**Pull request by deinhofer**
This PR adds support for the new modelManipulation.js and webAppUtils.js files and provides automatic model binding for widgets:

*   added/corrected links to new js libs:
*   added modelManipulation.js
*   added webAppUtils.js
*  removed wrong links to screencasts and tutorials in README.md

Currently your demo does not have input widgets, so you don't actually need the automatic synchronization between a widget and its bound plugin property.

To bind an input widget to a model property,  you would do as below (note **data-asterics-model-binding-1**):
```html
<input title="Mouse speed" type="range" id="speed" value="60" min="1" max="100" data-asterics-model-binding-1='{"componentKey": "Slider.1","propertyKey": "default"}'>
```

# Links
Template Repo Tutorial: https://github.com/asterics/AsTeRICS/wiki/AsTeRICS-Solution-Template-Repository
Javascript API: http://asterics.github.io/AsTeRICS/webapps/startpage/doc/lib-js-api/index.html

### CODE REVIEW

**Comment by deinhofer** [comment]
Please just check if everything still works and then merge. Don't modifiy demo to use new API.
Then we can add it to the github.io

**Comment by sabicalija** [comment]
Note: https://github.com/asterics/AsTeRICS/wiki/AsTeRICS-Solution-Template-Repository

**Review by sabicalija — APPROVED** [review]
Arduino demo tested and prepared for release/merge.
    
     - Remove/rename start.html to index.html, allowing `ant run` to start page separately
     - Remove ErrorCallbacks from Slider events when application is not running (Demo 3, Demo 5)
     - Add AsTeRICS Amazon link for servo motor

**Comment by deinhofer** [comment]
Awesome, excellent, very, very good work! :+1: 
The tutorial and the style is very cool!! :-)
ready for merge!

**Pull request merged**
